channels:
- conda-forge
dependencies:
- python=3.8.13
- pip<=21.0.1
- pip:
  - mlflow
  - cffi==1.15.0
  - cloudpickle==2.1.0
  - geopandas==0.10.2
  - matplotlib==3.5.2
  - python-dotenv==0.20.0
  - pytorch-lightning==1.6.3
  - rtree==1.0.0
  - scikit-learn==1.1.1
  - torch==1.11.0
  - torchvision==0.12.0
name: mlflow-env
